### ISSUE TITLE
Fix error that sometimes interrupts fetches from large profiles.

### ISSUE THREAD

**Issue by taylordohmen** [taylordohmen/dblp_fetch#4]
18:38:38.293 app.js:1 Uncaught (in promise) Error: Request failed, status 429
    at t [as constructor] (app.js:1:2108758)
    at mK (app.js:1:2108950)
    at app.js:1:2109629
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)
t @ app.js:1
mK @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1

**Comment by taylordohmen** [comment]
I'm pretty sure this happens when DBLP thinks I'm making too many api requests in a given time interval. It seems to happen much less often when my vpn is running...
